// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Core__Promise from "@rescript/core/src/Core__Promise.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return "";
      });
  var setEcho = match[1];
  React.useEffect((function () {
          Core__Promise.$$catch(fetch("http://localhost:8080/echo/hi").then(function (prim) {
                      return prim.json();
                    }).then(function (json) {
                    var obj = Js_json.decodeObject(json);
                    if (obj !== undefined) {
                      var value = Js_dict.get(obj, "echo");
                      if (value !== undefined) {
                        var echoText = Js_json.decodeString(value);
                        if (echoText !== undefined) {
                          setEcho(function (param) {
                                return echoText;
                              });
                        } else {
                          console.error("Value is not a string");
                        }
                      } else {
                        console.error("Could not find 'echo' field");
                      }
                    } else {
                      console.error("Invalid JSON object");
                    }
                    return Promise.resolve();
                  }), (function (err) {
                  console.error("Error fetching data:", err);
                  return Promise.resolve();
                }));
        }), []);
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("p", {
                    children: "Echo response: " + match[0]
                  })
            });
}

var make = App;

export {
  make ,
}
/* react Not a pure module */
