// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./pages/Home.res.mjs";
import * as Static from "./pages/Static.res.mjs";
import * as Dynamic from "./pages/Dynamic.res.mjs";
import * as Playground from "./pages/Playground.res.mjs";
import * as ReactRouterDom from "react-router-dom";
import * as JsxRuntime from "react/jsx-runtime";
import * as ReactRouterDOM$RescriptReactRouterDom from "rescript-react-router-dom/src/ReactRouterDOM.res.mjs";

function App(props) {
  return JsxRuntime.jsx(ReactRouterDom.HashRouter, {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsxs("nav", {
                            children: [
                              JsxRuntime.jsx(ReactRouterDOM$RescriptReactRouterDom.Link.make, {
                                    children: "Home",
                                    href: "/"
                                  }),
                              JsxRuntime.jsx(ReactRouterDOM$RescriptReactRouterDom.Link.make, {
                                    children: "Static",
                                    href: "/static"
                                  }),
                              JsxRuntime.jsx(ReactRouterDOM$RescriptReactRouterDom.Link.make, {
                                    children: "Dynamic",
                                    href: "/dynamic"
                                  }),
                              JsxRuntime.jsx(ReactRouterDOM$RescriptReactRouterDom.Link.make, {
                                    children: "Playground",
                                    href: "/playground"
                                  })
                            ]
                          }),
                      JsxRuntime.jsxs(ReactRouterDom.Routes, {
                            children: [
                              JsxRuntime.jsx(ReactRouterDom.Route, {
                                    path: "/",
                                    element: JsxRuntime.jsx(Home.make, {})
                                  }),
                              JsxRuntime.jsx(ReactRouterDom.Route, {
                                    path: "/static",
                                    element: JsxRuntime.jsx(Static.make, {})
                                  }),
                              JsxRuntime.jsx(ReactRouterDom.Route, {
                                    path: "/dynamic",
                                    element: JsxRuntime.jsx(Dynamic.make, {})
                                  }),
                              JsxRuntime.jsx(ReactRouterDom.Route, {
                                    path: "/playground",
                                    element: JsxRuntime.jsx(Playground.make, {})
                                  })
                            ]
                          })
                    ]
                  })
            });
}

var make = App;

export {
  make ,
}
/* Home Not a pure module */
