// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Game from "../components/Game.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Dynamic(props) {
  return JsxRuntime.jsx(Game.make, {
              mode: "dynamic"
            });
}

var make = Dynamic;

export {
  make ,
}
/* Game Not a pure module */
