// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "../components/Button.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as ReactRouterDOM$RescriptReactRouterDom from "rescript-react-router-dom/src/ReactRouterDOM.res.mjs";

function Home(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("h1", {
                            children: "Welcome to FP Strands!"
                          }),
                      JsxRuntime.jsx("p", {
                            children: "A project by Mia Choi, Emma Levitsky, Tam Nguyen, and David Wang."
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx(ReactRouterDOM$RescriptReactRouterDom.Link.make, {
                                    children: JsxRuntime.jsx(Button.make, {
                                          type_: "static",
                                          children: "Static Example"
                                        }),
                                    href: "/static"
                                  }),
                              JsxRuntime.jsx(ReactRouterDOM$RescriptReactRouterDom.Link.make, {
                                    children: JsxRuntime.jsx(Button.make, {
                                          type_: "dynamic",
                                          children: "Dynamic Example"
                                        }),
                                    href: "/dynamic"
                                  })
                            ],
                            className: "flex mt-5 gap-3"
                          })
                    ],
                    className: "items-center justify-center flex flex-col mb-10 h-full"
                  }),
              className: "content"
            });
}

var make = Home;

export {
  make ,
}
/* Button Not a pure module */
