// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Game from "../components/Game.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Static(props) {
  return JsxRuntime.jsx(Game.make, {
              mode: "static"
            });
}

var make = Static;

export {
  make ,
}
/* Game Not a pure module */
