// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Button(props) {
  var buttonClassName;
  switch (props.type_) {
    case "clear" :
        buttonClassName = "bg-red-600 hover:bg-red-700";
        break;
    case "dynamic" :
        buttonClassName = "bg-emerald-600 hover:bg-emerald-700";
        break;
    case "slides" :
        buttonClassName = "bg-amber-500 hover:bg-amber-600";
        break;
    case "static" :
        buttonClassName = "bg-cyan-600 hover:bg-cyan-700";
        break;
    case "submit" :
        buttonClassName = "bg-blue-600 hover:bg-blue-700";
        break;
    default:
      buttonClassName = "bg-gray-600 hover:bg-gray-700";
  }
  return JsxRuntime.jsx("button", {
              children: props.children,
              className: "inline-block px-6 py-2.5 text-white font-medium text-xs leading-tight uppercase rounded shadow-md focus:outline-none focus:ring-0 transition duration-150 ease-in-out " + buttonClassName
            });
}

var make = Button;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
