// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Theme(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h2", {
                      children: "Theme:",
                      className: "text-xl font-semibold text-center bg-sky-200 rounded-t-lg py-1"
                    }),
                JsxRuntime.jsx("h1", {
                      children: props.theme,
                      className: "px-5 py-4"
                    })
              ],
              className: "theme"
            });
}

var make = Theme;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
